### Mark Student
POST localhost:8080/task-grade/mark/5f510ad0-a4e3-4b6a-837d-f64ef0813ae5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInBob25lIjoiNDYyNyIsInN1YiI6IjQ2MjciLCJpYXQiOjE3NDk3MTg3NDAsImV4cCI6MTc0OTgwNTE0MH0.usS5udZDPu4JbxlQv_FRqwTuprW_2Tiv81k9PJoROZg

{
  "mark": 100
}

### Delete Marked Student
DELETE localhost:8080/task-grade/delete/542ef661-2da6-44b0-8e44-637017043da8
Authorization: Basic NDYyNzoxMjM=

### Update Marked Student
PUT localhost:8080/task-grade/update/f569e046-0385-4081-9729-c794ac0c187d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInBob25lIjoiNDYyNyIsInN1YiI6IjQ2MjciLCJpYXQiOjE3NDk3MTg3NDAsImV4cCI6MTc0OTgwNTE0MH0.usS5udZDPu4JbxlQv_FRqwTuprW_2Tiv81k9PJoROZg

{
  "mark": 69
}

### Get All Marked Students
GET localhost:8080/task-grade/all
Authorization: Basic NDYyNzoxMjM=

### Get Marked by ID
GET localhost:8080/task-grade/byId/f569e046-0385-4081-9729-c794ac0c187d
Authorization: Basic NDYyNzoxMjM=

###4627:123 -> NDYyNzoxMjM=